### ISSUE TITLE
Add all plugins to the wordpress installation

### ISSUE THREAD

**Issue by sopankhosla** [loklak/loklak_wordpress_plugins#1]

**Comment by sopankhosla** [comment]
436dfd3 and 3c09555 add all plugin directories. 
Closing for now.

**Comment by mariobehling** [comment]
Looks like they are not activated or configured.

![screenshot from 2016-08-03 18 56 24](https://cloud.githubusercontent.com/assets/1583873/17374249/0428d10a-59ac-11e6-9e2d-17c58abf65e5.png)

**Comment by sopankhosla** [comment]
This has been fixed. A dedicated issue to handle auto-deployment is opened [here](https://github.com/loklak/loklak_php_api/issues/49#issuecomment-238145136)
