### ISSUE TITLE
Add current plugin status readme

### ISSUE THREAD

**Issue by sopankhosla** [loklak/loklak_wordpress_plugins#2]

**Comment by sopankhosla** [comment]
4f8da1c adds it!

**Comment by mariobehling** [comment]
We have this now at different places. Please keep the relevant doc at this place now and link to it from elsewhere.

**Comment by sopankhosla** [comment]
Plugin information is added in [Plugin-Readme](https://github.com/loklak/loklak_wordpress_plugins/blob/master/Plugin-Readme.md)
This file has been linked from loklak_php_api [README.md](https://github.com/loklak/loklak_php_api#plugins-with-loklak-integration)

**Comment by sopankhosla** [comment]
Closing this issue. It has been solved ^
